// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;


/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
//  import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCVBu82TplL-_W7rWB6AXcXdDRNrc_6AwY',
    appId: '1:634701461232:web:04314431cb924b326a3435',
    messagingSenderId: '634701461232',
    projectId: 'proj1-b6489',
    authDomain: 'proj1-b6489.firebaseapp.com',
    storageBucket: 'proj1-b6489.appspot.com',
    measurementId: 'G-8KM21KED4G',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB4MjToClorbGrKyJClnJqHucevYGSNyVQ',
    appId: '1:634701461232:android:b8892f09927ff1416a3435',
    messagingSenderId: '634701461232',
    projectId: 'proj1-b6489',
    storageBucket: 'proj1-b6489.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBqvISvPGhCmoY5gzp4VIZZyBWwt6t9fac',
    appId: '1:634701461232:ios:94e8b6eec0c1c18c6a3435',
    messagingSenderId: '634701461232',
    projectId: 'proj1-b6489',
    storageBucket: 'proj1-b6489.appspot.com',
    iosClientId: '634701461232-ut25cvm7bbv2jferah4sfgo48q66blro.apps.googleusercontent.com',
    iosBundleId: 'com.example.proj1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBqvISvPGhCmoY5gzp4VIZZyBWwt6t9fac',
    appId: '1:634701461232:ios:94e8b6eec0c1c18c6a3435',
    messagingSenderId: '634701461232',
    projectId: 'proj1-b6489',
    storageBucket: 'proj1-b6489.appspot.com',
    iosClientId: '634701461232-ut25cvm7bbv2jferah4sfgo48q66blro.apps.googleusercontent.com',
    iosBundleId: 'com.example.proj1',
  );
}
